routes/admin.php
<?php


Route::get('/dash', 'Dashboard\DashboardController@index');
Route::resource('/users', 'User\IndexController');
// Active , deActive accounts ( user ) :-
Route::get('/active_account/{id}', 'Active\ActiveAccountController@index');
Route::get('/deActive_account/{id}', 'Active\ActiveAccountController@drActive_account');

Route::resource('/categories', 'Category\IndexController');
Route::resource('/categories.subcategory', 'Category\SubCategoryController');


Route::resource('/notifications', 'Notification\IndexController');
Route::get('/userNotifiy/{id}', 'User\UserNotificationController@index');
Route::post('/userNotifiyStore', 'User\UserNotificationController@userNotifiyStore');

Route::resource('/settings', 'Setting\IndexController');//

//books
Route::resource('/books', 'Book\IndexController');//
Route::resource('/audio_books', 'AudioBook\IndexController');//
Route::resource('/books.comments', 'Book\CommentController');//
Route::resource('/books.rates', 'Book\RateController');//
Route::resource('/topics', 'Topic\IndexController');//
Route::resource('/articles', 'Article\IndexController');//
Route::resource('/articles.comments', 'Article\CommentsController');//

Route::resource('/openScreens', 'openScreen\IndexController');
Route::resource('/requested-books', 'Requestedbooks\IndexController');
Route::resource('/downloads', 'Download\IndexController');

Route::get('/userTopics/{id}', 'User\IndexController@topics');


Route::post('/getCategories', 'Ajax\IndexController@getCategories');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::post('/getCategories', 'Admin\Ajax\IndexController@getCategories');
Route::get('/', 'Admin\Auth\LoginController@index');
Route::get('/admin', 'Admin\Auth\LoginController@index');
Route::post('/adminlogin', 'Admin\Auth\LoginController@adminlogin');
Route::post('/adminlogout', 'Admin\Auth\LoginController@adminlogout');

Route::get('/forget/{token}', 'Admin\Auth\LoginController@forget');
Route::post('/change-password', 'Admin\Auth\LoginController@changepassword');
Route::get('/password_updated_done/{id}', 'Admin\Auth\LoginController@password_updated_done');

Route::prefix('api')
    ->middleware(['api', 'lang'])
    ->group(function () {
        Route::post('register', [\App\Http\Controllers\Api\RegisterController::class, 'index']);
        Route::post('login', [\App\Http\Controllers\Api\LoginController::class, 'index']);
        Route::post('login-with-facebook', [\App\Http\Controllers\Api\LoginWithFacebookController::class, 'index']);
        Route::post('forget-password', [\App\Http\Controllers\Api\ForgetPasswordController::class, 'index']);
        Route::post('introduction-messages', [\App\Http\Controllers\Api\IntroductionMessagesController::class, 'index']);
        Route::post('topics', [\App\Http\Controllers\Api\TopicsController::class, 'index']);
        Route::post('books', [\App\Http\Controllers\Api\BooksController::class, 'index']);
        Route::post('audio-books', [\App\Http\Controllers\Api\AudioBooksController::class, 'index']);
        Route::post('book-details', [\App\Http\Controllers\Api\BookDetailsController::class, 'index']);
        Route::post('audio-book-details', [\App\Http\Controllers\Api\AudioBookDetailsController::class, 'index']);
        Route::post('book-comments', [\App\Http\Controllers\Api\BookCommentsController::class, 'index']);
        Route::post('our-picks', [\App\Http\Controllers\Api\OurPicksController::class, 'index']);
        Route::post('home-page-articles', [\App\Http\Controllers\Api\HomePageArticlesController::class, 'index']);
        Route::post('your-pen-page-articles', [\App\Http\Controllers\Api\YourPenPageArticlesController::class, 'index']);
        Route::post('article-details', [\App\Http\Controllers\Api\ArticleDetailsController::class, 'index']);
        Route::post('article-comments', [\App\Http\Controllers\Api\ArticleCommentsController::class, 'index']);
        Route::post('categories', [\App\Http\Controllers\Api\CategoriesController::class, 'index']);
        Route::post('sub-categories', [\App\Http\Controllers\Api\SubCategoriesController::class, 'index']);
        Route::post('request-book', [\App\Http\Controllers\Api\RequestBookController::class, 'index']);
        Route::post('most-viewed-books', [\App\Http\Controllers\Api\MostViewedBooksController::class, 'index']);
        Route::post('report-book', [\App\Http\Controllers\Api\ReportBookController::class, 'index']);
        Route::post('search-books', [\App\Http\Controllers\Api\SearchBooksController::class, 'index']);
        Route::post('user-profile', [\App\Http\Controllers\Api\UserProfileController::class, 'index']);
        Route::post('article-comment-replies', [\App\Http\Controllers\Api\ArticleCommentRepliesController::class, 'index']);
        Route::post('user-followings', [\App\Http\Controllers\Api\AllFollowingsController::class, 'index']);
        Route::post('user-followers', [\App\Http\Controllers\Api\AllFollowersController::class, 'index']);

        // Miss Password
        /*Route::post('/forgetPassword', 'ResetPassword\IndexController@index');*/
    });

app/Models/Article.php
<?php

namespace App\Models;

use App\Http\Controllers\FilesHandler;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory, FilesHandler;

    protected $fillable = [
        "image",
        "title",
        "body",
        "audio_url",
        "book_id",
        "userId",
        'no_likes',
        'no_dislikes',
        'no_comments',
        'no_views',
        'no_shares',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, "userId");
    }

    public function book()
    {
        return $this->belongsTo(Book::class, "book_id");
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, "articleId");
    }

  /*  public function setImageAttribute($value)
    {
        if ($value and is_file($value)) {
            $path = $this->storeFile($value);
            //dd($path);
            $this->attributes['image'] = url("storage/app/" . strtolower($path)) ;
        }
    }*/
    public function getDashBookAttribute()
    {
        $att = null;
        if ($this->book)
            $att = $this->book->dash_name;
        return $att;
    }
}

app/Models/UserTopic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserTopic extends Model
{
    use HasFactory;

    protected $fillable = [
        "user_id",
        "topic_id",
    ];

    public function topic()
    {
        return $this->belongsTo(Topic::class, 'topic_id');
    }

    public function getDashTopicAttribute()
    {
        $att = null;
        if ($this->topic)
            $att = $this->topic->dash_name;
        return $att;
    }  public function getDashImageAttribute()
    {
        $att = null;
        if ($this->topic)
            $att = $this->topic->image;
        return $att;
    }
}

app/Http/Controllers/Admin/Article/CommentsController.php
<?php

    namespace App\Http\Controllers\Admin\Article;

    use App\Categories;
    use App\Models\BookComment;
    use App\Models\Category;
    use App\Models\Comment;
    use App\Models\SubCategory;
    use App\Product;
    use App\Store_his_categories;
    use App\Traits\storeImage;
    use App\User;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;

    class CommentsController extends Controller
    {
        use storeImage;

        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index($article_id)
        {
            $items = Comment::where('articleId', $article_id)->orderBy("id", "desc")->paginate(10);
            //dd($items);
            return view('admin.articles.comments.index', compact('article_id', 'items'));
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create($category_id)
        {
            //dd($category_id);
            $category = Category::findorfail($category_id);
            //dd($category);
            return view('admin.categories.subcategory.create', compact('category'));
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
     /*   public function store(Request $request, $category_id)
        {
            $data = $request->validate([
                'subCategoryName' => 'required',
            ]);

            $data["categoryId"] = $category_id;
            $item = SubCategory::create($data);
            session()->flash('success', trans('language.done'));
            return redirect("admin/categories/$category_id/subcategory");
        }*/


        /**
         * Display the specified resource.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */


        public function edit($category_id, $subcategory_id)
        {
            $category = Category::find($category_id);
            $item = SubCategory::find($subcategory_id);
            return view('admin.categories.subcategory.edit', compact('category',  'item'));
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $category_id, $subcategory_id)
        {
            $data = $request->validate([
                'subCategoryName' => '',
            ]);
            $item = SubCategory::find($subcategory_id);
            dd($item);
            $item->update($data);
            session()->flash('success', trans('language.done'));
            return redirect("admin/categories/$category_id/subcategory");

        }

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function destroy($book_id, $id)
        {
            $comments = Comment::findOrFail($id);
            $comments->delete();
            session()->flash('success', trans('language.done'));
            return back();
        }
    }

app/Http/Controllers/Admin/Article/IndexController.php
<?php

    namespace App\Http\Controllers\Admin\Article;

    use App\Models\Article;
    use App\Models\Book;
    use App\Models\Category;
   ;
    use App\Traits\storeImage;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;

    class IndexController extends Controller
    {
        use storeImage;


        public function index(Request $request)
        {
            $items = Article::query();
            $items = $this->filter($request, $items);
            return view('admin.articles.index', compact('items'));

        }

        public function filter($request, $items)
        {
            if ($request->title) {
                $items = $items->where("title", 'LIKE', '%' . $request->title . '%');
            }
            if ($request->book_id) {
                $items = $items->where("book_id", $request->book_id);
            }
            $items = $items->orderBy("id", "desc")->paginate(10);
            return $items;
        }


        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()

        {

            return view('admin.articles.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
            $data = $request->all();
            if ($request->image) {
                $data['image'] = $this->storeImage($request->image);
            }
           // dd($data);
            $book = Article::create($data);


            session()->flash('success', trans('language.done'));
            return redirect(url('/admin/articles'));
        }

        /**
         * Display the specified resource.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {/*
        $items = Categories::findOrFail($id);
        return view('admin.Categories.show',compact('items'));*/
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            $item = Article::findOrFail($id);
            return view('admin.articles.edit', compact('item'));
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $id)
        {
            $item = Article::findOrFail($id);
            $data = $request->all();
            if ($request->imgURL) {
                $data['imgURL'] = $this->storeImage($request->imgURL);
            }
            $item->update($data);
            session()->flash('success', trans('language.done'));
            return redirect(url('/admin/articles'));
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            $item = Article::findOrFail($id)->delete();
            session()->flash('success', trans('language.done'));
            return redirect(url('/admin/articles'));
        }
    }

resources/views/admin/articles/create.blade.php
@extends('admin.layout.forms.add.index')
@section('action' , "articles")
@section('title' , trans('language.add'))
@section('page-title',trans('language.articles'))
@section('form-groups')
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.name'),'name'=>'title', 'placeholder'=>trans('language.name_ar'),'valid'=>trans('language.vaildation')])

    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{trans('language.body')}}</h4>
                <textarea id="body" name="body"></textarea>
            </div>
        </div>
    </div>


    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.audio_url'),'name'=>'audio_url', 'placeholder'=>trans('language.audio_url'),'valid'=>trans('language.vaildation')])

    @includeIf('admin.components.form.add.file', ['icon' => 'fa fa-check','label' => trans('language.image'),'name'=>'image', 'max'=>'2'])

    @includeIf('admin.components.form.add.select', ['label' => trans("language.books"),'name'=>'book_id', 'items'=> \App\Models\Book::all() , 'icon' => 'fa fa-list',])
    @includeIf('admin.components.form.add.select', ['label' => trans("language.user"),'name'=>'userId', 'items'=> \App\Models\User::all() , 'icon' => 'fa fa-list',])

@endsection
@section('submit-button-title' ,trans('language.add'))
@section('extra_js')


    <!-- wysuhtml5 Plugin JavaScript -->


    <script>
        $(document).ready(function () {


            $('#body').summernote();

        });

    </script>




@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layout.forms.edit.index')
@section('action' , "articles/$item->id")
@section('title' , trans('language.edit'))
@section('page-title',trans('language.articles'))
@section('form-groups')
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.name'),'name'=>'title', 'placeholder'=>trans('language.name_ar'),'valid'=>trans('language.vaildation')])

    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{trans('language.body')}}</h4>
                <textarea id="body" name="body">{{$item->body}}</textarea>
            </div>
        </div>
    </div>


    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.audio_url'),'name'=>'audio_url', 'placeholder'=>trans('language.audio_url'),'valid'=>trans('language.vaildation')])

    @includeIf('admin.components.form.edit.file', ['icon' => 'fa fa-check','label' => trans('language.image'),'name'=>'image', 'max'=>'2'])

    @includeIf('admin.components.form.edit.select', ['label' => trans("language.books"),'name'=>'book_id', 'items'=> \App\Models\Book::all() , 'icon' => 'fa fa-list',])
    @includeIf('admin.components.form.edit.select', ['label' => trans("language.user"),'name'=>'userId', 'items'=> \App\Models\User::all() , 'icon' => 'fa fa-list',])

@endsection
@section('submit-button-title' ,trans('language.add'))
@section('extra_js')


    <!-- wysuhtml5 Plugin JavaScript -->


    <script>
        $(document).ready(function () {


            $('#body').summernote();

        });

    </script>




@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layout.table.index')
@section('page-title',trans('language.categories'))
@section('buttons')

@stop
@section('nav')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url("admin/")}}">  {{trans('language.home')}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{trans('language.articles')}}</li>
    </ol>
@endsection
@section('thead')
    <th>#</th>
    <th>{{trans('language.title')}}</th>
    <th>{{trans('language.content_article')}}</th>
    <th>{{trans('language.book_name')}}</th>
    <th>{{trans('language.comments')}}</th>
{{--
    <th>{{trans('language.image')}}</th>
--}}
    <th>{{trans('language.settings')}}</th>
@endsection
@section('tbody')
    @foreach($items as $item)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{$item->title}}</td>
            <td>
                <p style="display: inline">{!! substr($item->body,0,50) !!}
                </p>  @includeIf("admin.components.buttons.showPop",["message" => $item->body ])

            </td>

            <td>{{$item->dash_book}}</td>
            <td>

                @includeIf("admin.components.buttons.custom" , ["href" => "articles/$item->id/comments", 'class' => 'bi bi-bell' , 'title'=> trans('language.comments'), 'feather' => 'list'])

            </td>
{{--
            <td> @includeIf("admin.components.image.index" , ["url" => $item->image])</td>
--}}

            <td>
                @includeIf("admin.components.buttons.edit" , ["href" => "articles/$item->id/edit"])

                @includeIf("admin.components.buttons.delete",["message" => "" ,  "action" => url("admin/articles/$item->id")])

            </td>
        </tr>
    @endforeach
@endsection

@section("filters")
    <form method="get" action="{{url("/admin/articles/")}}">

        <div style="display: flex">
            <div class="col-md-3">
                <input type="text" class="form-control name_input " name="title" value="{{request()->title}}"
                       placeholder="{{trans('language.title')}}">
            </div>
            <div class="col-md-3">
                <select required class="form-control" name="book_id">
                    <option value="0">{{trans('language.book_name')}}</option>
                    @foreach(\App\Models\Book::all() as $book)
                        <option value="{{$book->id}}">{{$book->bookName}}</option>
                    @endforeach
                </select>
                {{--
                                @includeIf('admin.components.form.add.select', ['label' => trans("language.country"),'name'=>'country_id', 'items'=> \App\Models\Category::all() , 'icon' => 'fa fa-list',])
                --}}

            </div>

            <div class="col-md-3">
                <input style="width: 45%" type="submit" class="btn btn-success " value="{{trans('language.filter')}}">
                <button style="width: 45%" type="button"
                        class="btn btn-info  reset_inputs ">{{trans('language.reset')}}</button>
            </div>
        </div>
    </form>
@stop

@section("extra_js")

    <script>
        $('.reset_inputs').click(function () {
            $('.name_input').val('');

        });
    </script>

@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.layout.table.index')
@section('page-title',trans('language.categories'))
@section('buttons')

@stop
@section('thead')
    <th>#</th>
    <th>{{trans('language.image')}}</th>
    <th>{{trans('language.category')}}</th>
    <th>{{trans('language.addsubcategory')}}</th>
    <th>{{trans('language.settings')}}</th>
@endsection
@section('tbody')
    @foreach($items as $item)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td> @includeIf("admin.components.image.index" , ["url" => $item->dash_image])</td>
            <td>{{$item->dash_name}}</td>
            <td>@includeIf("admin.components.buttons.addbtn" , ["href" => "categories/$item->id/subcategory",'class' => 'info' , 'title'=> trans('language.addsubcategory') ])</td>
            <td>
                @includeIf("admin.components.buttons.edit" , ["href" => "categories/$item->id/edit"])

                @includeIf("admin.components.buttons.delete",["message" => "" ,  "action" => url("admin/categories/$item->id")])

            </td>
        </tr>
    @endforeach
@endsection